"""last

Revision ID: 472b691c90d8
Revises: 2ed494e41e98
Create Date: 2024-07-03 14:28:32.316110

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472b691c90d8'
down_revision: Union[str, None] = '2ed494e41e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviceTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_type')
    )
    op.create_table('deviceModels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deviceType_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deviceType_id'], ['deviceTypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_model')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vlan_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlan_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('deviceModel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deviceModel_id'], ['deviceModels.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('credentials', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('credentials', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('sites', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('sites', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    op.drop_column('users', 'create_at')
    op.drop_column('sites', 'modified_at')
    op.drop_column('sites', 'create_at')
    op.drop_column('credentials', 'modified_at')
    op.drop_column('credentials', 'create_at')
    op.drop_table('devices')
    op.drop_table('vlans')
    op.drop_table('deviceModels')
    op.drop_table('deviceTypes')
    # ### end Alembic commands ###
