"""Auto generate after editing

Revision ID: 64bab30e9014
Revises: 01211261db77
Create Date: 2024-07-03 12:46:46.626101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bab30e9014'
down_revision: Union[str, None] = '01211261db77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorization', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authorization')
    # ### end Alembic commands ###
